CREATE TABLE `classroom`.`registration` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(24) NULL DEFAULT NULL,
  `firstname` VARCHAR(48) NULL DEFAULT NULL,`lastname` VARCHAR(48) NULL DEFAULT NULL,`emailid` VARCHAR(48) NULL DEFAULT NULL,
  `password` VARCHAR(48) NULL,`created_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;