CREATE TABLE `classroom`.`registration` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `studendid` VARCHAR(24) NULL DEFAULT NULL, `username` VARCHAR(24) NULL DEFAULT NULL,
  `firstname` VARCHAR(48) NULL DEFAULT NULL,`lastname` VARCHAR(48) NULL DEFAULT NULL,`emailid` VARCHAR(48) NULL DEFAULT NULL,
  `password` VARCHAR(48) NULL,`created_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;
  
  CREATE TABLE `digimags`.`academicwiki` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `articlename` VARCHAR(24) NULL DEFAULT NULL, `studentname` VARCHAR(24) NULL DEFAULT NULL,
  `pdfname` VARCHAR(48) NULL DEFAULT NULL,`link` VARCHAR(48) NULL DEFAULT NULL,`resource` VARCHAR(48) NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;
  
  
    CREATE TABLE `digimags`.`platform` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `discussionName` VARCHAR(128) NULL DEFAULT NULL, `firstname` VARCHAR(24) NULL DEFAULT NULL,
  `lastname` VARCHAR(48) NULL DEFAULT NULL,`tags` VARCHAR(48) NULL DEFAULT NULL,`username` VARCHAR(48) NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;
  
     CREATE TABLE `digimags`.`platformdiscussion` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `ordervalue` int(3) NULL DEFAULT NULL, `value` VARCHAR(1024) NULL DEFAULT NULL, `platformid` BIGINT(20) NOT NULL,`username` VARCHAR(24) NULL DEFAULT NULL,
    `firstname` VARCHAR(24) NULL DEFAULT NULL,
  `lastname` VARCHAR(48) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;
  
  
  CREATE TABLE `digimags`.`virtualhuddle` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `huddlename` VARCHAR(24) NULL DEFAULT NULL, `selectdate` DATETIME NULL DEFAULT NULL,
  `description` VARCHAR(48) NULL DEFAULT NULL,`huddleplace` VARCHAR(48) NULL DEFAULT NULL,`subscribed` boolean NULL DEFAULT false,
  `created_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;
  
    CREATE TABLE `digimags`.`subscribe` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `huddleid` BIGINT(20) NULL DEFAULT 0, `userid` BIGINT(20) NULL DEFAULT 0,
  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;
  
  